// Shared mock data + tokens for all brainrouter design directions

const BR_TOKENS = {
  bg: '#0b0e13',
  bg2: '#11151c',
  bg3: '#161b24',
  panel: '#141923',
  border: '#1f2632',
  borderHi: '#2a3343',
  text: '#e6edf6',
  textDim: '#8693a8',
  textMute: '#5a6679',
  // accents (oklch-tuned, kept close to source neons)
  green: '#22d39a',
  greenDim: 'rgba(34,211,154,0.14)',
  cyan: '#3ec5ff',
  cyanDim: 'rgba(62,197,255,0.14)',
  violet: '#9d7bff',
  violetDim: 'rgba(157,123,255,0.16)',
  amber: '#f5b14a',
  amberDim: 'rgba(245,177,74,0.16)',
  red: '#ff6b6b',
  redDim: 'rgba(255,107,107,0.14)',
  pink: '#ff7ac6',
  pinkDim: 'rgba(255,122,198,0.14)',
};

const SOURCES = {
  discord: { label: 'Discord', color: BR_TOKENS.violet, glyph: 'D' },
  signal: { label: 'Signal', color: BR_TOKENS.cyan, glyph: 'S' },
  local: { label: 'Local', color: BR_TOKENS.green, glyph: 'L' },
};

const HARNESSES = {
  omp: { label: 'OMP', color: BR_TOKENS.green },
  droid: { label: 'Droid', color: BR_TOKENS.cyan },
  cc: { label: 'Claude Code', color: BR_TOKENS.violet },
  opencode: { label: 'OpenCode', color: BR_TOKENS.amber },
  vibe: { label: 'Vibe', color: BR_TOKENS.pink },
};

const MODELS = {
  'claude-sonnet-4-6': { label: 'claude-sonnet-4-6', color: BR_TOKENS.violet, kind: 'cloud', provider: 'anthropic' },
  'claude-opus-4-6':   { label: 'claude-opus-4-6',   color: BR_TOKENS.violet, kind: 'cloud', provider: 'anthropic' },
  'qwen3.6-27b-heretic': { label: 'qwen3.6-27b-heretic', color: BR_TOKENS.cyan, kind: 'local', provider: 'llama-swap' },
  'gpt-5.2-mini':      { label: 'gpt-5.2-mini',      color: BR_TOKENS.green,  kind: 'cloud', provider: 'openai' },
  'glm-4.6-air':       { label: 'glm-4.6-air',       color: BR_TOKENS.amber,  kind: 'local', provider: 'llama-swap' },
};

// Live tasks. status: queued|routing|generating|reviewing|approved|escalated|failed
const BR_TASKS = [
  {
    id: 'tsk_8f2a',
    taskId: 'feature-20260504-013',
    folder: 'brainrouter',
    source: 'discord',
    sourceMeta: '@adrien · #brainrouter',
    harness: 'omp',
    route: 'cloud-direct',
    model: 'claude-sonnet-4-6',
    prompt: 'Add deploy/adrien-setup.sh — idempotent setup script. Installs brainrouter on port 9100, bun, OMP, llama-server-toolbox.',
    status: 'generating',
    progress: 0.62,
    startedAt: '16s ago',
    latencyMs: 4600,
    tokens: { in: 12400, out: 8210 },
    streamingHint: 'Generating · writing systemd unit file',
    review: {
      reviewer: 'claude-opus-4-6',
      status: 'pending',
    },
  },
  {
    id: 'tsk_3693',
    taskId: 'feature-20260503-001',
    folder: 'brainrouter',
    source: 'discord',
    sourceMeta: '@adrien · DM',
    harness: 'omp',
    route: 'cloud-auto',
    model: 'claude-opus-4-6',
    prompt: 'Wrapper to install brainrouter, bonsai, manifest, llama-cpp, toolbox for user adrien.',
    status: 'reviewing',
    progress: 1,
    startedAt: '13m ago',
    latencyMs: 2600,
    tokens: { in: 18200, out: 14800 },
    review: {
      reviewer: 'claude-opus-4-6',
      status: 'escalated',
      iters: 5,
      lastFeedback: 'Critical: Hardcoded API Key (Security). Line 30 contains a plaintext Manifest API key.',
      summary: 'Added deploy/adrien-setup.sh — idempotent setup script. Configures systemd user service and OMP agent configs.',
    },
  },
  {
    id: 'tsk_5a5c',
    taskId: 'fix-20260504-001',
    folder: 'brainrouter',
    source: 'local',
    sourceMeta: 'CLI · /home/papa/.omp',
    harness: 'omp',
    route: 'local-auto',
    model: 'qwen3.6-27b-heretic',
    prompt: 'Patch llama-swap healthcheck timeout from 60s to 300s for cold-start GLM-4.6.',
    status: 'approved',
    progress: 1,
    startedAt: '7:14 PM',
    latencyMs: 1300,
    tokens: { in: 4100, out: 2900 },
    review: {
      reviewer: 'claude-opus-4-6',
      status: 'approved',
      iters: 0,
    },
  },
  {
    id: 'tsk_df3f',
    taskId: 'feature-20260503-002',
    folder: 'ninja-tv',
    source: 'signal',
    sourceMeta: '+1 415 ··· 0421',
    harness: 'cc',
    route: 'cloud-direct',
    model: 'claude-sonnet-4-6',
    prompt: 'Make a card game I can play on loungemaxxing.com — assets in @assets/. Same counter concept and random unlocks.',
    status: 'generating',
    progress: 0.31,
    startedAt: '2m ago',
    latencyMs: 6800,
    tokens: { in: 22100, out: 4200 },
    streamingHint: 'Generating · designing weapon-tree.jsx',
    review: {
      reviewer: 'claude-opus-4-6',
      status: 'pending',
    },
  },
  {
    id: 'tsk_b21e',
    taskId: 'fix-20260504-002',
    folder: 'omp',
    source: 'local',
    sourceMeta: 'CLI · /home/papa/code/omp',
    harness: 'droid',
    route: 'local-direct',
    model: 'glm-4.6-air',
    prompt: 'Refactor token-counter to handle MoE draft heads.',
    status: 'queued',
    progress: 0,
    startedAt: 'just now',
    latencyMs: 0,
    tokens: { in: 0, out: 0 },
    review: { reviewer: '—', status: 'pending' },
  },
  {
    id: 'tsk_c9aa',
    taskId: 'feature-20260503-014',
    folder: 'loungemaxxing',
    source: 'signal',
    sourceMeta: '+1 628 ··· 7711',
    harness: 'vibe',
    route: 'cloud-auto',
    model: 'claude-sonnet-4-6',
    prompt: 'Add a Discord bot command to ping the harness queue depth.',
    status: 'reviewing',
    progress: 1,
    startedAt: '24m ago',
    latencyMs: 3100,
    tokens: { in: 9800, out: 5200 },
    review: {
      reviewer: 'claude-opus-4-6',
      status: 'iterating',
      iters: 2,
      lastFeedback: 'Style: prefer slash-commands over prefix-commands in this codebase.',
    },
  },
  {
    id: 'tsk_71ef',
    taskId: 'fix-20260502-009',
    folder: 'brainrouter',
    source: 'discord',
    sourceMeta: '@adrien · #ops',
    harness: 'omp',
    route: 'cloud-direct',
    model: 'claude-opus-4-6',
    prompt: 'Bonsai is misclassifying short prompts as local. Bump cloud bias.',
    status: 'failed',
    progress: 0.4,
    startedAt: '38m ago',
    latencyMs: 8800,
    tokens: { in: 3300, out: 800 },
    review: { reviewer: '—', status: 'failed' },
    failReason: 'Manifest 502 — fell back to llama-swap, then aborted.',
  },
];

// Aggregate stats (matches the original dashboard cards)
const BR_STATS = {
  total: 225,
  cloudAuto: 11,
  localAuto: 6,
  directLocal: 4,
  directCloud: 204,
  fallbacks: 3,
  avgLatency: '3.4s',
};

// Sankey nodes/links: source → harness → route → model
// Numbers are roughly proportional and sum-consistent enough to look honest.
const BR_SANKEY = {
  sources:   [['discord', 138], ['signal', 41], ['local', 46]],
  harnesses: [['omp', 162], ['cc', 24], ['droid', 18], ['vibe', 12], ['opencode', 9]],
  routes:    [['cloud-direct', 138], ['cloud-auto', 36], ['local-auto', 28], ['local-direct', 23]],
  models:    [['claude-sonnet-4-6', 96], ['claude-opus-4-6', 58], ['qwen3.6-27b-heretic', 34], ['glm-4.6-air', 22], ['gpt-5.2-mini', 15]],
  // links arr: [fromKey, toKey, value]
  links: [
    ['discord','omp',102],['discord','cc',20],['discord','vibe',10],['discord','droid',6],
    ['signal','omp',32],['signal','cc',4],['signal','vibe',2],['signal','opencode',3],
    ['local','omp',28],['local','droid',12],['local','opencode',6],
    ['omp','cloud-direct',96],['omp','cloud-auto',26],['omp','local-auto',22],['omp','local-direct',18],
    ['cc','cloud-direct',20],['cc','cloud-auto',4],
    ['droid','local-direct',12],['droid','local-auto',6],
    ['vibe','cloud-direct',8],['vibe','cloud-auto',4],
    ['opencode','cloud-direct',5],['opencode','cloud-auto',2],['opencode','local-direct',2],
    ['cloud-direct','claude-sonnet-4-6',82],['cloud-direct','claude-opus-4-6',48],['cloud-direct','gpt-5.2-mini',8],
    ['cloud-auto','claude-sonnet-4-6',14],['cloud-auto','claude-opus-4-6',10],['cloud-auto','gpt-5.2-mini',7],['cloud-auto','qwen3.6-27b-heretic',5],
    ['local-auto','qwen3.6-27b-heretic',16],['local-auto','glm-4.6-air',12],
    ['local-direct','qwen3.6-27b-heretic',13],['local-direct','glm-4.6-air',10],
  ],
};

const BR_HEALTH = {
  llamaSwap: { ver: '211', up: true, latency: '4ms' },
  llamaCpp:  { ver: '9025', up: true, latency: '3ms' },
  toolbox:   { ver: 'v43', up: true, latency: '6ms' },
  manifest:  { ver: '2026-05-01 · 9d2dad4', up: true, latency: '142ms' },
  bridges:   { discord: { up: true, msgs: 0, hrs: 50.4 }, signal: { up: true, msgs: 0, hrs: 50.4 } },
};

window.BR = { TOKENS: BR_TOKENS, SOURCES, HARNESSES, MODELS, TASKS: BR_TASKS, STATS: BR_STATS, SANKEY: BR_SANKEY, HEALTH: BR_HEALTH };
